# @package _global_

defaults:
  - override /model: baselines
  - _self_
class_name: 'city'
model:
  network:
    head:
      instance:
        id_to_gps: ${dataset.train_dataset.path}index_to_gps_${class_name}.pt
max_epochs: 1
mode: eval
is_baseline: true
