# @package _global_

defaults:
  - override /model: classification
  - override /model/network: lora_backbone
  - override /model/network/backbone: openclip_B_32
  - _self_

class_name: country
is_baseline: false

lora_r: 16
lora_alpha: 256
lora_dropout: 0.1
lora_bias: lora_only
