# @package _global_

defaults:
  - override /model: hybrid_sharedreg
  - override /model/network/backbone: openclip_B_32
  - _self_

class_name: 'adaptive_quadtree_10_5000'
is_baseline: false
max_epochs: 15

dataset:
  global_batch_size: 2048
