# @package _global_

defaults:
  - override /model: multi
  - override /model/network: multi_task
  - override /model/network/backbone: openclip_B_32
  - _self_

model:
  optimizer:
    optim:
      lr: 2e-4
      weight_decay: 0.0001
    backbone_lr: 2e-5

aux_data: ['land_cover','drive_side','climate','soil','dist_sea'] #'road_index'
mode: 'train'
is_baseline: false
max_epochs: 15
